from core.voice import speaker
import random
from pygame import mixer

mixer.init()


jokes = [
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "I'm reading a book about anti-gravity. It's impossible to put down.",
    "I used to play piano by ear, but now I use my hands.",
    "I know they say money talks, but mine just waves goodbye.",
    "I told a joke about a pencil once… it had no point.",
    "I was going to tell a time-travel joke, but you didn't like it.",
    "I accidentally swallowed some food coloring. The doctor says I'm OK, but I feel like I’ve dyed a little inside.",
    "I'm on a seafood diet. I see food and I eat it.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "Parallel lines have so much in common… it’s a shame they’ll never meet.",
    "What do you call a fish with no eyes? Fsh.",
    "Why do cows wear bells? Because their horns don’t work.",
    "What do you call a dog that can do magic? A labracadabrador.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the duck go to therapy? It was feeling a little down.",
    "What’s a cat’s favorite color? Purr-ple.",
    "Why can’t you trust a lion? Because they're always lion.",
    "Where do polar bears vote? The North Poll.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why did the crab never share? Because he was shellfish.",
    "Why can’t you trust atoms? Because they make up everything.",
    "I would tell you a chemistry joke, but I know I wouldn’t get a reaction.",
    "Schrödinger’s cat walks into a bar… and doesn’t.",
    "How do you organize a space party? You planet.",
    "Never trust a math teacher with graph paper — they’re always plotting something.",
    "Why did the photon check no bags? It was traveling light.",
    "What do you call an educated tube? A graduated cylinder.",
    "Why did the bacteria break up? There was no chemistry.",
    "I asked the librarian if they had books on paranoia. She whispered, 'They're right behind you.'",
    "Black holes are where God divided by zero.",
    "Why do Java developers wear glasses? Because they don’t C#.",
    "I would tell you a UDP joke, but you might not get it.",
    "I told my computer I needed a break… and now it won’t stop sending me vacation ads.",
    "I asked Siri why I'm single. It activated the front camera.",
    "There are 10 types of people in the world: those who understand binary and those who don’t.",
    "Why was the computer cold? It left its Windows open.",
    "What did the router say to the doctor? 'It hurts when IP.'",
    "I just changed my password to 'incorrect,' so when I forget it, the computer reminds me.",
    "AI told me a joke once. It was machine-learned humor. Terrible, but improving.",
    "Why did the coder get kicked out of school? Too many class exceptions.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "I don’t trust tacos… they tend to spill the beans.",
    "What do you call cheese that isn’t yours? Nacho cheese.",
    "Why don’t eggs tell jokes? They’d crack each other up.",
    "I buttered up the toast… now it’s in love with me.",
    "Did you hear about the carrot detective? He got to the root of every case.",
    "What did the grape do when it got stepped on? Nothing. It just let out a little wine.",
    "Why did the coffee file a police report? It got mugged.",
    "What do you call an angry pea? A grump-pea.",
    "If you boil a funny bone, you get a laughing stock. That’s humerus.",
    "Want to hear a construction joke? I’m still working on it.",
    "I used to hate facial hair… but then it grew on me.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "I used to be addicted to the hokey pokey, but I turned myself around.",
    "What do you call a pile of cats? A meowtain.",
    "Why can't your nose be 12 inches long? Because then it would be a foot.",
    "My wife asked me to stop impersonating a flamingo. I had to put my foot down.",
    "What do you call someone with no body and no nose? Nobody nose.",
    "I'm reading a book on glue – I just can't put it down.",
    "Why did the wizard get a job in IT? Because he was good at spell-check.",
    "Dragons never finish their meals — they always leave a bit burnt.",
    "Why don’t vampires go to barbecues? They don't like steaks.",
    "Why did the elf go to school? To improve his elf-esteem.",
    "What's a zombie's least favorite room? The living room.",
    "What do ghosts serve at parties? Booze.",
    "What kind of music do mummies listen to? Wrap music.",
    "Why did the troll bring a ladder to the bar? To get over the bridge.",
    "What did the knight say after losing his sword? 'I’ve been disarmed!'",
    "Why did the hobbit sit at the bar all day? He was Tolkien too much.",
    "I invented a new word: Plagiarism.",
    "Why did the bicycle fall over? It was two-tired.",
    "I told my suitcase we weren’t going on vacation. Now it’s dealing with emotional baggage.",
    "What do you call a fake noodle? An impasta.",
    "I once tried to catch some fog… I mist.",
    "What do you call a belt made of watches? A waist of time.",
    "I was wondering why the frisbee kept getting bigger… and then it hit me.",
    "I started a band called 999 Megabytes — we haven’t gotten a gig yet.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "I tried to make a pencil with two erasers. It was pointless.",
    "Why was the math book sad? It had too many problems.",
    "Why did the student eat his homework? The teacher said it was a piece of cake.",
    "What’s a pirate’s favorite subject? Arrrrt.",
    "Why did the history teacher always tell dad jokes? Because he lived in the past.",
    "I failed my spelling test. Now I’m just 'lameented.'",
    "Why was the teacher cross-eyed? She couldn’t control her pupils.",
    "What’s a geometry teacher’s favorite kind of tree? A 'geome-tree.'",
    "What’s a student’s favorite dance? The test-tango.",
    "Why was the book in therapy? Too much character development.",
    "My pencil broke during the exam. It was pointless, just like studying.",
    "This joke is like a broken pencil… pointless.",
    "I told myself I’d stop telling bad jokes. But I’m not *pun*ctual.",
    "I downloaded a joke app. It crashed. Even that was funnier than the jokes.",
    "You’re not going to laugh at this joke. That’s the punchline.",
    "This joke is under construction. Please laugh responsibly.",
    "I thought of a clever joke about jokes, but I forgot the setup.",
    "I have a joke about recursion… see joke 97.",
    "My humor is like a Wi-Fi signal — strong in one room, nonexistent in another.",
    "You want a clever joke? Check back in 5 minutes. AI update pending.",
    "I told 99 jokes, but the last one is still buffering..."
]


def joke(ui):
    mixer.music.load('sounds/joke.mp3')
    joke = random.choice(jokes)
    print(joke)
    ui.showResponseTextSignal.emit(joke)
    speaker.yap(joke)
    mixer.music.play()

